FE/.babelrc, FE/.eslintrc.js, FE/.gitignore, FE/package-lock.json, FE/package.json, FE/src/index.html, FE/tsconfig.json, FE/webpack.config.js
- Close #10
- typescript 설치
- @typescript-eslint/eslint-plugin, @typescript-eslint/parser : 타입스크립트와 eslint 연동
- eslint 설치
- eslint-config-airbnb-base: 에어비앤비 설정
- eslint-config-airbnb-typescript: 에어비앤비 설정을 타입스크립트로
- 제대로 작동하는지는 모르겠음!
=> [#10] Chore: 개발환경 구축

FE/src/css/main.css, FE/src/index.html
- Close #4 
- 모달 레이어, 사이드 메뉴 제외
=> [#4] Style: 메인 CSS 스타일링

FE/src/css/main.css, FE/src/index.html
- Close #17 
- Close #7 : 메인 페이지 CSS 하며 해결함. 코드가 필요없는 부분이었음.
=> 사이드 메뉴 CSS 작성 완료

FE/src/css/main.css, FE/src/index.html
- Close #14 
- Close #13 : 작업하면서 이슈 완료
=> [#14] 모달 레이어 CSS 작성

BE/src/main/java/com/codesquad/todo/domain/Activity.java, BE/src/main/java/com/codesquad/todo/domain/Card.java, BE/src/main/java/com/codesquad/todo/domain/Project.java, BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java, BE/src/main/java/com/codesquad/todo/domain/Section.java, BE/src/main/java/com/codesquad/todo/domain/User.java, BE/src/main/resources/data.sql, BE/src/main/resources/schema.sql
- project table 추가
- 각 테이블 간 관계 변경
=> [#23] update: db 재설계

iOS/.gitignore, iOS/README.md, iOS/Todo/Todo.xcodeproj/project.pbxproj, iOS/Todo/Todo.xcodeproj/project.xcworkspace/contents.xcworkspacedata, iOS/Todo/Todo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, iOS/Todo/Todo/AppDelegate.swift, iOS/Todo/Todo/Assets.xcassets/AppIcon.appiconset/Contents.json, iOS/Todo/Todo/Assets.xcassets/Contents.json, iOS/Todo/Todo/Base.lproj/LaunchScreen.storyboard, iOS/Todo/Todo/Base.lproj/Main.storyboard, iOS/Todo/Todo/Info.plist, iOS/Todo/Todo/SceneDelegate.swift, iOS/Todo/Todo/ViewController.swift, iOS/Todo/TodoTests/Info.plist, iOS/Todo/TodoTests/TodoTests.swift
=> [#22] 스토리보드로 화면 구성

BE/src/main/java/com/codesquad/todo/domain/User.java, BE/src/main/resources/application.properties, BE/src/main/resources/data.sql, BE/src/main/resources/schema.sql
- user를 root로 변경
- user 와 project 1:N 관계
- project가 section list 와 activity list를 가짐
- section이 card list를 가짐
=> [#23] fix: db 변경

BE/src/main/java/com/codesquad/todo/domain/Activity.java, BE/src/main/java/com/codesquad/todo/domain/Card.java, BE/src/main/java/com/codesquad/todo/domain/Project.java, BE/src/main/resources/schema.sql
Activity
- Card card, User user 를 String 으로 수정
Card  
- deleted 삭제  
Project  
- Set User 삭제
=> [#23] DB 수정시 변경되지 않은 도메인 수정

FE/src/css/components/_textarea.css, FE/src/ts/components/card.ts, FE/src/ts/components/eventManager.ts, FE/src/ts/components/fetch.ts, FE/src/ts/components/inputForm.ts, FE/src/ts/components/modal.ts, FE/webpack.config.js
- Close #11 
- 우선은 모달을 거치지 않고 바로 삭제하는 기능 구현
- 이후 진행사항은 #12 에서 진행
=> [#10] 할 일 카드 삭제 기능 구현

FE/src/css/components/_dimmedLayer.css, FE/src/css/components/_header.css, FE/src/css/components/_modal.css, FE/src/index.html, FE/src/ts/components/card.ts, FE/src/ts/components/column.ts, FE/src/ts/components/container.ts, FE/src/ts/components/eventManager.ts, FE/src/ts/components/fetch.ts, FE/src/ts/components/inputForm.ts, FE/src/ts/components/modal.ts, FE/src/ts/main.ts, FE/src/ts/utils/constants.ts, FE/src/ts/utils/htmlElement.ts
- Close #11, Close #12 
- 전반적인 리팩토링 포함
=> [#11] 카드 삭제 기능 구현

BE/build.gradle, BE/src/main/java/com/codesquad/todo/HttpInterceptor.java, BE/src/main/java/com/codesquad/todo/WebConfig.java, BE/src/main/java/com/codesquad/todo/domain/Project.java, BE/src/main/java/com/codesquad/todo/domain/User.java, BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java, BE/src/main/java/com/codesquad/todo/exeption/NotFoundData.java, BE/src/main/java/com/codesquad/todo/service/JwtService.java, BE/src/main/resources/data.sql
=> Interceptor를 이용한 jwt token 인증 시스템 구현

FE/src/css/components/_card.css, FE/src/ts/components/card.ts, FE/src/ts/components/column.ts, FE/src/ts/components/columnWrap.ts, FE/src/ts/components/container.ts, FE/src/ts/components/eventManager.ts, FE/src/ts/components/fetch.ts, FE/src/ts/components/header.ts, FE/src/ts/components/inputForm.ts, FE/src/ts/components/modal.ts, FE/src/ts/main.ts, FE/src/ts/utils/utils.ts, FE/tsconfig.json
=> [#15] 카드 수정 기능 구현

BE/src/main/java/com/codesquad/todo/controller/CardController.java, BE/src/main/java/com/codesquad/todo/domain/Project.java, BE/src/main/java/com/codesquad/todo/domain/SectionRepository.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java
- RequestMapping 변경
- Section repository 이용해서 카드에 접근하기
- Project.class 내부에서 activity 추가
=> [#29] 카드 삭제 기능 추가

BE/src/main/java/com/codesquad/todo/WebConfig.java
/api/**에서 /api/column/** 으로 수정
=> Interceptor PathPatterns 수정

BE/src/main/java/com/codesquad/todo/controller/CardController.java, BE/src/main/java/com/codesquad/todo/domain/Activity.java, BE/src/main/java/com/codesquad/todo/domain/SectionRepository.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java
=> [#28] 카드 수정 로직 구현

BE/src/main/java/com/codesquad/todo/HttpInterceptor.java, BE/src/main/java/com/codesquad/todo/SimpleCorsFilter.java, BE/src/main/java/com/codesquad/todo/WebConfig.java, BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java
=> 헤더 추가 후 cors 문제

BE/src/main/java/com/codesquad/todo/HttpInterceptor.java, BE/src/main/java/com/codesquad/todo/SimpleCorsFilter.java, BE/src/main/java/com/codesquad/todo/WebConfig.java, BE/src/main/java/com/codesquad/todo/controller/TodoController.java, BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java
=> [#67] filter 추가

BE/src/main/java/com/codesquad/todo/controller/TodoController.java, BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java, BE/src/main/java/com/codesquad/todo/domain/Section.java, BE/src/main/java/com/codesquad/todo/dto/CardDto.java, BE/src/main/java/com/codesquad/todo/dto/SectionDto.java, BE/src/main/java/com/codesquad/todo/dto/TempSectionDTO.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java
1. List<TempSectionDto>에 section들을 매핑
2. 위 리스트를 돌면서 각 section id에 해당하는 Card를 가져와 CardDto에 넣음 
3. 위 CardDto를 SectionDto에 있는 List<CardDto>에 넣어줌
설명이 횡설수설하다아..!!
=> [#31] 전체 목록 출력

BE/src/main/java/com/codesquad/todo/controller/ActivityController.java, BE/src/main/java/com/codesquad/todo/controller/CardController.java, BE/src/main/java/com/codesquad/todo/controller/TodoController.java, BE/src/main/java/com/codesquad/todo/domain/Activity.java, BE/src/main/java/com/codesquad/todo/exeption/UnauthorizedException.java, BE/src/main/java/com/codesquad/todo/service/JwtService.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java, BE/src/main/java/com/codesquad/todo/utill/Action.java, BE/src/main/java/com/codesquad/todo/utill/ErrorMessages.java, BE/src/main/java/com/codesquad/todo/utill/SuccessMessages.java
=> [#77] refactor: 스트링 하드 코딩 제외

BE/src/main/java/com/codesquad/todo/controller/TodoController.java, BE/src/main/java/com/codesquad/todo/domain/Activity.java, BE/src/main/java/com/codesquad/todo/domain/ActivityRepository.java, BE/src/main/java/com/codesquad/todo/domain/CardRepository.java, BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java, BE/src/main/java/com/codesquad/todo/dto/TempSectionDTO.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java
- 의미를 좀 더 명확하게 전달할 수 있게 바꿔봤는데 뭐든 애매한거 같다아
=> [#77] 함수, 변수명 정리

FE/src/css/components/_button.css, FE/src/css/components/_card.css, FE/src/css/components/_column.css, FE/src/css/components/_textarea.css, FE/src/css/utils/_utilClasses.css, FE/src/ts/components/card.ts, FE/src/ts/components/column.ts, FE/src/ts/components/columnWrap.ts, FE/src/ts/components/dragAndDrop.ts, FE/src/ts/components/eventManager.ts, FE/src/ts/components/fetch.ts, FE/src/ts/components/modal.ts, FE/src/ts/main.ts, FE/src/ts/utils/constants.ts, FE/src/ts/utils/htmlElement.ts, FE/src/ts/utils/utils.ts
- Close #16 
- 실제로 '다른 위치로 이동이 이루어졌는지' (시작지점과 도착지점이 다른지) 에 대한 검증이 제대로 이루어지지 않음.
- 사이드 바 구현 후, 액티비티 출력하는 과정에서 수정할 예정
=> [#16] 드래그 앤 드롭 기능 구현

BE/src/main/java/com/codesquad/todo/controller/CardController.java, BE/src/main/java/com/codesquad/todo/domain/Section.java, BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java, BE/src/main/java/com/codesquad/todo/service/TodoService.java, BE/src/main/java/com/codesquad/todo/utill/SuccessMessages.java
source와 destination의 값이 같은 경우를 조건문으로 처리한게 신경쓰임
(동일한 로직으로 처리하면 이미 존재하는 index라고 에러남)
조건문 없이 동일한 로직으로 처리하고 싶은데.. 그럼 root인 project에서 처리하면 될까?
resolve: #30
=> [#30] feat: 카드 이동

FE/src/css/components/_column.css, FE/src/css/components/_dimmedLayer.css, FE/src/css/components/_modal.css, FE/src/css/components/_sidemenu.css, FE/src/css/utils/_utilClasses.css, FE/src/index.html, FE/src/ts/components/activity.ts, FE/src/ts/components/card.ts, FE/src/ts/components/column.ts, FE/src/ts/components/columnWrap.ts, FE/src/ts/components/dragAndDrop.ts, FE/src/ts/components/eventManager.ts, FE/src/ts/components/fetch.ts, FE/src/ts/components/header.ts, FE/src/ts/components/inputForm.ts, FE/src/ts/components/modal.ts, FE/src/ts/components/sidemenu.ts, FE/src/ts/main.ts, FE/src/ts/utils/constants.ts, FE/src/ts/utils/htmlElement.ts, FE/src/ts/utils/utils.ts
=> [#18] 사이드 메뉴 구현
